plugins { id 'com.android.application' }

android {
    namespace 'com.jugoconsulting.planedit'
    compileSdk 35
    defaultConfig {
        applicationId 'com.jugoconsulting.planedit'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
